services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local:7778';
        gitlab_rails['gitlab_signup_enabled'] = 'true';
        # Отключаем HTTPS для локальной разработки
        nginx['redirect_http_to_https'] = false;
        # Можно указать явный порт для nginx (по умолчанию 80 внутри контейнера)
        nginx['listen_port'] = 80;
    ports:
      - "7778:80"
      - "443:443"
      - "22:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab-network
    shm_size: '256m'

#  gitlab-runner:
#    image: gitlab/gitlab-runner:latest
#    container_name: gitlab-runner
#    restart: unless-stopped
#    depends_on:
#      - gitlab
#    volumes:
#      - gitlab_runner_config:/etc/gitlab-runner
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - gitlab-network

networks:
  gitlab-network:
    driver: bridge

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
#  gitlab_runner_config: